

import Path from 'node:path'
import * as Fs from 'node:fs'

import { test, describe, afterEach } from 'node:test'
import assert from 'node:assert'
import { createLiveTransport } from '../../live-runner'
import { runLiveEntity } from '../../live-entity'


import { GitlabSDK, BaseFeature, stdutil } from '../../..'

import {
  envOverride,
  liveClientOptions,
  liveDelay,
  loadEnvLocal,
  makeCtrl,
  makeMatch,
  makeReqdata,
  makeStepData,
  makeValid,
  maybeSkipControl,
} from '../../utility'


loadEnvLocal(__dirname + '/../../../.env.local')


describe('ApiEntitiesRelationImportTrackerEntity', async () => {

  // Per-test live pacing. Delay is read from sdk-test-control.json's
  // `test.live.delayMs`; only sleeps when GITLAB_TEST_LIVE=TRUE.
  afterEach(liveDelay('GITLAB_TEST_LIVE'))

  test('instance', async () => {
    const testsdk = GitlabSDK.test()
    const ent = testsdk.ApiEntitiesRelationImportTracker()
    assert(null != ent)
  })


  test('basic', async (t) => {

    const live = 'TRUE' === process.env.GITLAB_TEST_LIVE
    for (const op of ['create']) {
      if (!live && maybeSkipControl(t, 'entityOp', 'api_entities_relation_import_tracker.' + op, live)) return
    }

    
    const setup = basicSetup()
    if (setup.live) {
      return runLiveEntity(setup, {"active":true,"alias":{"field":{}},"fields":{},"name":"api_entities_relation_import_tracker","op":{"create":{"input":"data","name":"create","points":[{"a":true,"co":{"id":"POST /api/v4/projects/import-relation","source":"swagger2","version":2},"g":{"query":[{"a":true,"k":"query","n":"file","or":"file","r":true,"t":"`$ANY`","index$":0},{"a":true,"k":"query","n":"file_etag","or":"file_etag","r":false,"t":"`$ANY`","index$":1},{"a":true,"k":"query","n":"file_md5","or":"file_md5","r":false,"t":"`$ANY`","index$":2},{"a":true,"k":"query","n":"file_name","or":"file_name","r":false,"t":"`$ANY`","index$":3},{"a":true,"k":"query","n":"file_path","or":"file_path","r":false,"t":"`$ANY`","index$":4},{"a":true,"k":"query","n":"file_remote_id","or":"file_remote_id","r":false,"t":"`$STRING`","index$":5},{"a":true,"k":"query","n":"file_remote_url","or":"file_remote_url","r":false,"t":"`$ANY`","index$":6},{"a":true,"k":"query","n":"file_sha1","or":"file_sha1","r":false,"t":"`$ANY`","index$":7},{"a":true,"k":"query","n":"file_sha256","or":"file_sha256","r":false,"t":"`$ANY`","index$":8},{"a":true,"k":"query","n":"file_size","or":"file_size","r":false,"t":"`$ANY`","index$":9},{"a":true,"k":"query","n":"file_type","or":"file_type","r":false,"t":"`$ANY`","index$":10},{"a":true,"k":"query","n":"path","or":"path","r":true,"t":"`$STRING`","index$":11},{"a":true,"k":"query","n":"relation","or":"relation","r":true,"t":"`$ANY`","index$":12}]},"k":"http","m":"POST","o":"/api/v4/projects/import-relation","q":{"exist":["file","file_etag","file_md5","file_name","file_path","file_remote_id","file_remote_url","file_sha1","file_sha256","file_size","file_type","path","relation"]},"r":{},"s":[{"lit":"api"},{"lit":"v4"},{"lit":"projects"},{"lit":"import-relation"}],"t":{"req":"`reqdata`","res":"`body`"},"index$":0}],"key$":"create"}},"relations":{"ancestors":[]},"key$":"api_entities_relation_import_tracker","name__orig":"api_entities_relation_import_tracker","Name":"ApiEntitiesRelationImportTracker","name_":"api_entities_relation_import_tracker","name-":"api-entities-relation-import-tracker","NAME":"API_ENTITIES_RELATION_IMPORT_TRACKER","index$":148}, {"active":true,"entity":"api_entities_relation_import_tracker","key$":"BasicApiEntitiesRelationImportTrackerFlow","kind":"basic","name":"BasicApiEntitiesRelationImportTrackerFlow","param":{},"step":[{"a":true,"d":{},"i":{"ref":"api_entities_relation_import_tracker_ref01"},"m":{},"o":"create","s":[],"v":[],"index$":0}]}, 'ApiEntitiesRelationImportTracker', {"POST /api/v4/projects/import-relation":{"protocol":"http","parameters":[{"in":"formData","name":"path","description":"The project path and name","type":"string","required":true,"index$":0},{"in":"formData","name":"file","description":"The project export file from which to extract the relation.","type":"file","required":true,"index$":1},{"in":"formData","name":"relation","description":"The relation to import. Must be one of issues, merge_requests, ci_pipelines, or milestones.","type":"string","required":true,"index$":2},{"in":"formData","name":"file.path","description":"Path to locally stored body (generated by Workhorse)","type":"string","required":false,"index$":3},{"in":"formData","name":"file.name","description":"Real filename as sent in Content-Disposition (generated by Workhorse)","type":"string","required":false,"index$":4},{"in":"formData","name":"file.type","description":"Real content type as send in Content-Type (generated by Workhorse)","type":"string","required":false,"index$":5},{"in":"formData","name":"file.size","description":"Real size of file (generated by Workhorse)","type":"integer","format":"int32","required":false,"index$":6},{"in":"formData","name":"file.md5","description":"MD5 checksum of the file (generated by Workhorse)","type":"string","required":false,"index$":7},{"in":"formData","name":"file.sha1","description":"SHA1 checksum of the file (generated by Workhorse)","type":"string","required":false,"index$":8},{"in":"formData","name":"file.sha256","description":"SHA256 checksum of the file (generated by Workhorse)","type":"string","required":false,"index$":9},{"in":"formData","name":"file.etag","description":"Etag of the file (generated by Workhorse)","type":"string","required":false,"index$":10},{"in":"formData","name":"file.remote_id","description":"Remote_id of the file (generated by Workhorse)","type":"string","required":false,"index$":11},{"in":"formData","name":"file.remote_url","description":"Remote_url of the file (generated by Workhorse)","type":"string","required":false,"index$":12}]}})
    }
    const client = setup.client
    const struct = setup.struct

    const isempty = struct.isempty
    const select = struct.select


    // CREATE
    const api_entities_relation_import_tracker_ref01_ent = client.ApiEntitiesRelationImportTracker()
    let api_entities_relation_import_tracker_ref01_data = setup.data.new.api_entities_relation_import_tracker['api_entities_relation_import_tracker_ref01']

    api_entities_relation_import_tracker_ref01_data = (await api_entities_relation_import_tracker_ref01_ent.create(api_entities_relation_import_tracker_ref01_data)).data()
    assert(null != api_entities_relation_import_tracker_ref01_data)


  })
})



function basicSetup(extra?: any) {
  // TODO: fix test def options
  const options: any = {} // null

  // TODO: needs test utility to resolve path
  const entityDataFile =
    Path.resolve(__dirname, 
      '../../../../.sdk/test/entity/api_entities_relation_import_tracker/ApiEntitiesRelationImportTrackerTestData.json')

  // TODO: file ready util needed?
  const entityDataSource = Fs.readFileSync(entityDataFile).toString('utf8')

  // TODO: need a xlang JSON parse utility in voxgig/struct with better error msgs
  const entityData = JSON.parse(entityDataSource)

  options.entity = entityData.existing

  let client = GitlabSDK.test(options, extra)
  const struct = client.utility().struct
  const merge = struct.merge
  const transform = struct.transform

  let idmap = transform(
    ['api_entities_relation_import_tracker01','api_entities_relation_import_tracker02','api_entities_relation_import_tracker03'],
    {
      '`$PACK`': ['', {
        '`$KEY`': '`$COPY`',
        '`$VAL`': ['`$FORMAT`', 'upper', '`$COPY`']
      }]
    })

  const env = envOverride({
    'GITLAB_TEST_API_ENTITIES_RELATION_IMPORT_TRACKER_ENTID': idmap,
    'GITLAB_TEST_LIVE': 'FALSE',
    'GITLAB_TEST_EXPLAIN': 'FALSE',
    'GITLAB_APIKEY': '',
  })

  idmap = env['GITLAB_TEST_API_ENTITIES_RELATION_IMPORT_TRACKER_ENTID']

  const live = 'TRUE' === env.GITLAB_TEST_LIVE

  const transport = createLiveTransport()
  if (live) {
    const rawIds = process.env['GITLAB_TEST_API_ENTITIES_RELATION_IMPORT_TRACKER_ENTID']
    idmap = rawIds && rawIds.trim() ? JSON.parse(rawIds) : {}
    if (!idmap || Array.isArray(idmap) || typeof idmap !== 'object') {
      throw new Error('Live ENTID must be a JSON object')
    }
    client = new GitlabSDK(merge([
      // FIRST, so the generated fields below win: sdk-test-control.json's
      // test.client.options adds to the live client, it does not redirect it.
      liveClientOptions(),
      {
        apikey: env.GITLAB_APIKEY,
      },
      // 'extra || {}', not a bare 'extra': struct.merge returns UNDEFINED when the
      // last entry is undefined, and basicSetup is normally called with no
      // argument at all - so a bare 'extra' silently discarded the apikey
      // and server values above and handed the SDK undefined. Harmless
      // while there was nothing in that object; not harmless now.
      extra || {},
      { system: { fetch: transport.fetch } }
    ]))
  }

  const setup = {
    idmap,
    env,
    options,
    client,
    struct,
    data: entityData,
    explain: 'TRUE' === env.GITLAB_TEST_EXPLAIN,
    live,
    transport,
    now: Date.now(),
  }

  return setup
}
  
