

import Path from 'node:path'
import * as Fs from 'node:fs'

import { test, describe, afterEach } from 'node:test'
import assert from 'node:assert'
import { createLiveTransport } from '../../live-runner'
import { runLiveEntity } from '../../live-entity'


import { GitlabSDK, BaseFeature, stdutil } from '../../..'

import {
  envOverride,
  liveClientOptions,
  liveDelay,
  loadEnvLocal,
  makeCtrl,
  makeMatch,
  makeReqdata,
  makeStepData,
  makeValid,
  maybeSkipControl,
} from '../../utility'


// AFTER the imports on purpose: TypeScript hoists `import` above any
// statement in the emitted CommonJS, so a loader placed above them would
// run only after every imported module had already been evaluated - and
// anything reading process.env at module scope would miss these values.
loadEnvLocal(__dirname + '/../../../.env.local')


describe('ApiEntitiesRelationImportTrackerEntity', async () => {

  // Per-test live pacing. Delay is read from sdk-test-control.json's
  // `test.live.delayMs`; only sleeps when GITLAB_TEST_LIVE=TRUE.
  afterEach(liveDelay('GITLAB_TEST_LIVE'))

  test('instance', async () => {
    const testsdk = GitlabSDK.test()
    const ent = testsdk.ApiEntitiesRelationImportTracker()
    assert(null != ent)
  })


  test('basic', async (t) => {

    const live = 'TRUE' === process.env.GITLAB_TEST_LIVE
    for (const op of ['create']) {
      if (!live && maybeSkipControl(t, 'entityOp', 'api_entities_relation_import_tracker.' + op, live)) return
    }

    
    const setup = basicSetup()
    if (setup.live) {
      return runLiveEntity(setup, {"active":true,"alias":{"field":{}},"fields":[],"name":"api_entities_relation_import_tracker","op":{"create":{"input":"data","name":"create","points":[{"active":true,"args":{"query":[{"active":true,"kind":"query","name":"file","orig":"file","reqd":true,"type":"`$ANY`","index$":0},{"active":true,"kind":"query","name":"file_etag","orig":"file_etag","reqd":false,"type":"`$ANY`","index$":1},{"active":true,"kind":"query","name":"file_md5","orig":"file_md5","reqd":false,"type":"`$ANY`","index$":2},{"active":true,"kind":"query","name":"file_name","orig":"file_name","reqd":false,"type":"`$ANY`","index$":3},{"active":true,"kind":"query","name":"file_path","orig":"file_path","reqd":false,"type":"`$ANY`","index$":4},{"active":true,"kind":"query","name":"file_remote_id","orig":"file_remote_id","reqd":false,"type":"`$STRING`","index$":5},{"active":true,"kind":"query","name":"file_remote_url","orig":"file_remote_url","reqd":false,"type":"`$ANY`","index$":6},{"active":true,"kind":"query","name":"file_sha1","orig":"file_sha1","reqd":false,"type":"`$ANY`","index$":7},{"active":true,"kind":"query","name":"file_sha256","orig":"file_sha256","reqd":false,"type":"`$ANY`","index$":8},{"active":true,"kind":"query","name":"file_size","orig":"file_size","reqd":false,"type":"`$ANY`","index$":9},{"active":true,"kind":"query","name":"file_type","orig":"file_type","reqd":false,"type":"`$ANY`","index$":10},{"active":true,"kind":"query","name":"path","orig":"path","reqd":true,"type":"`$STRING`","index$":11},{"active":true,"kind":"query","name":"relation","orig":"relation","reqd":true,"type":"`$ANY`","index$":12}]},"contract":{"id":"POST /api/v4/projects/import-relation","json":"{\"consumes\":[\"multipart/form-data\"],\"operationId\":\"postApiV4ProjectsImportRelation\",\"parameters\":[{\"description\":\"The project path and name\",\"in\":\"formData\",\"name\":\"path\",\"required\":true,\"type\":\"string\"},{\"description\":\"The project export file from which to extract the relation.\",\"in\":\"formData\",\"name\":\"file\",\"required\":true,\"type\":\"file\"},{\"description\":\"The relation to import. Must be one of issues, merge_requests, ci_pipelines, or milestones.\",\"in\":\"formData\",\"name\":\"relation\",\"required\":true,\"type\":\"string\"},{\"description\":\"Path to locally stored body (generated by Workhorse)\",\"in\":\"formData\",\"name\":\"file.path\",\"required\":false,\"type\":\"string\"},{\"description\":\"Real filename as sent in Content-Disposition (generated by Workhorse)\",\"in\":\"formData\",\"name\":\"file.name\",\"required\":false,\"type\":\"string\"},{\"description\":\"Real content type as send in Content-Type (generated by Workhorse)\",\"in\":\"formData\",\"name\":\"file.type\",\"required\":false,\"type\":\"string\"},{\"description\":\"Real size of file (generated by Workhorse)\",\"format\":\"int32\",\"in\":\"formData\",\"name\":\"file.size\",\"required\":false,\"type\":\"integer\"},{\"description\":\"MD5 checksum of the file (generated by Workhorse)\",\"in\":\"formData\",\"name\":\"file.md5\",\"required\":false,\"type\":\"string\"},{\"description\":\"SHA1 checksum of the file (generated by Workhorse)\",\"in\":\"formData\",\"name\":\"file.sha1\",\"required\":false,\"type\":\"string\"},{\"description\":\"SHA256 checksum of the file (generated by Workhorse)\",\"in\":\"formData\",\"name\":\"file.sha256\",\"required\":false,\"type\":\"string\"},{\"description\":\"Etag of the file (generated by Workhorse)\",\"in\":\"formData\",\"name\":\"file.etag\",\"required\":false,\"type\":\"string\"},{\"description\":\"Remote_id of the file (generated by Workhorse)\",\"in\":\"formData\",\"name\":\"file.remote_id\",\"required\":false,\"type\":\"string\"},{\"description\":\"Remote_url of the file (generated by Workhorse)\",\"in\":\"formData\",\"name\":\"file.remote_url\",\"required\":false,\"type\":\"string\"}],\"produces\":[\"application/json\"],\"protocol\":\"http\",\"responses\":{\"201\":{\"description\":\"Re-import a relation into a project\",\"schema\":{\"description\":\"API_Entities_RelationImportTracker model\",\"properties\":{\"created_at\":{\"example\":\"2022-01-31T15:10:45.080Z\",\"format\":\"date-time\",\"type\":\"string\"},\"id\":{\"example\":1,\"format\":\"int32\",\"type\":\"integer\"},\"project_path\":{\"example\":\"namespace1/project1\",\"type\":\"string\"},\"relation\":{\"example\":\"issues\",\"type\":\"string\"},\"status\":{\"example\":\"pending\",\"type\":\"string\"},\"updated_at\":{\"example\":\"2022-01-31T15:10:45.080Z\",\"format\":\"date-time\",\"type\":\"string\"}},\"type\":\"object\"}},\"400\":{\"description\":\"Bad request\"},\"401\":{\"description\":\"Unauthorized\"},\"403\":{\"description\":\"Forbidden\"},\"404\":{\"description\":\"Not found\"},\"503\":{\"description\":\"Service unavailable\"}},\"securitySchemes\":{\"access_token_header\":{\"in\":\"header\",\"name\":\"PRIVATE-TOKEN\",\"type\":\"apiKey\"},\"access_token_query\":{\"in\":\"query\",\"name\":\"private_token\",\"type\":\"apiKey\"}},\"securitySource\":\"unspecified\"}","source":"swagger2","version":1},"kind":"http","method":"POST","orig":"/api/v4/projects/import-relation","segments":[{"lit":"api"},{"lit":"v4"},{"lit":"projects"},{"lit":"import-relation"}],"select":{"exist":["file","file_etag","file_md5","file_name","file_path","file_remote_id","file_remote_url","file_sha1","file_sha256","file_size","file_type","path","relation"]},"transform":{"req":"`reqdata`","res":"`body`"},"index$":0}],"key$":"create"}},"relations":{"ancestors":[]},"key$":"api_entities_relation_import_tracker","name__orig":"api_entities_relation_import_tracker","Name":"ApiEntitiesRelationImportTracker","name_":"api_entities_relation_import_tracker","name-":"api-entities-relation-import-tracker","NAME":"API_ENTITIES_RELATION_IMPORT_TRACKER","index$":148}, {"active":true,"entity":"api_entities_relation_import_tracker","key$":"BasicApiEntitiesRelationImportTrackerFlow","kind":"basic","name":"BasicApiEntitiesRelationImportTrackerFlow","param":{},"step":[{"active":true,"data":{},"input":{"ref":"api_entities_relation_import_tracker_ref01"},"match":{},"op":"create","spec":[],"valid":[],"index$":0}]}, 'ApiEntitiesRelationImportTracker')
    }
    const client = setup.client
    const struct = setup.struct

    const isempty = struct.isempty
    const select = struct.select


    // CREATE
    const api_entities_relation_import_tracker_ref01_ent = client.ApiEntitiesRelationImportTracker()
    let api_entities_relation_import_tracker_ref01_data = setup.data.new.api_entities_relation_import_tracker['api_entities_relation_import_tracker_ref01']

    api_entities_relation_import_tracker_ref01_data = (await api_entities_relation_import_tracker_ref01_ent.create(api_entities_relation_import_tracker_ref01_data)).data()
    assert(null != api_entities_relation_import_tracker_ref01_data)


  })
})



function basicSetup(extra?: any) {
  // TODO: fix test def options
  const options: any = {} // null

  // TODO: needs test utility to resolve path
  const entityDataFile =
    Path.resolve(__dirname, 
      '../../../../.sdk/test/entity/api_entities_relation_import_tracker/ApiEntitiesRelationImportTrackerTestData.json')

  // TODO: file ready util needed?
  const entityDataSource = Fs.readFileSync(entityDataFile).toString('utf8')

  // TODO: need a xlang JSON parse utility in voxgig/struct with better error msgs
  const entityData = JSON.parse(entityDataSource)

  options.entity = entityData.existing

  let client = GitlabSDK.test(options, extra)
  const struct = client.utility().struct
  const merge = struct.merge
  const transform = struct.transform

  let idmap = transform(
    ['api_entities_relation_import_tracker01','api_entities_relation_import_tracker02','api_entities_relation_import_tracker03'],
    {
      '`$PACK`': ['', {
        '`$KEY`': '`$COPY`',
        '`$VAL`': ['`$FORMAT`', 'upper', '`$COPY`']
      }]
    })

  const env = envOverride({
    'GITLAB_TEST_API_ENTITIES_RELATION_IMPORT_TRACKER_ENTID': idmap,
    'GITLAB_TEST_LIVE': 'FALSE',
    'GITLAB_TEST_EXPLAIN': 'FALSE',
    'GITLAB_APIKEY': '',
  })

  idmap = env['GITLAB_TEST_API_ENTITIES_RELATION_IMPORT_TRACKER_ENTID']

  const live = 'TRUE' === env.GITLAB_TEST_LIVE

  const transport = createLiveTransport()
  if (live) {
    const rawIds = process.env['GITLAB_TEST_API_ENTITIES_RELATION_IMPORT_TRACKER_ENTID']
    idmap = rawIds && rawIds.trim() ? JSON.parse(rawIds) : {}
    if (!idmap || Array.isArray(idmap) || typeof idmap !== 'object') {
      throw new Error('Live ENTID must be a JSON object')
    }
    client = new GitlabSDK(merge([
      // FIRST, so the generated fields below win: sdk-test-control.json's
      // test.client.options adds to the live client, it does not redirect it.
      liveClientOptions(),
      {
        apikey: env.GITLAB_APIKEY,
      },
      // 'extra || {}', not a bare 'extra': struct.merge returns UNDEFINED when the
      // last entry is undefined, and basicSetup is normally called with no
      // argument at all - so a bare 'extra' silently discarded the apikey
      // and server values above and handed the SDK undefined. Harmless
      // while there was nothing in that object; not harmless now.
      extra || {},
      { system: { fetch: transport.fetch } }
    ]))
  }

  const setup = {
    idmap,
    env,
    options,
    client,
    struct,
    data: entityData,
    explain: 'TRUE' === env.GITLAB_TEST_EXPLAIN,
    live,
    transport,
    now: Date.now(),
  }

  return setup
}
  
