# Typed models for the Gitlab SDK.
#
# GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
# params (op.<name>.points[].args.params[]). Field/param types come from the
# canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
# @voxgig/apidef VALID_CANON). Do not edit by hand.
#
# These are TypedDicts, not dataclasses: the SDK ops return/accept plain dicts
# at runtime, and a TypedDict IS a dict shape, so the types match the runtime.
# Optional (req:false) keys are modelled as TypedDict key-optionality
# (total=False), split into a required base + total=False subclass when a type
# has both required and optional keys.

from __future__ import annotations

from typing import TypedDict, Any


class ApiEntitiesProjectWithAccess(TypedDict, total=False):
    allow_merge_on_skipped_pipeline: bool
    allow_pipeline_trigger_approve_deployment: bool
    analytics_access_level: str
    approvals_before_merge: str
    archived: bool
    auto_cancel_pending_pipelines: str
    auto_devops_deploy_strategy: str
    auto_devops_enabled: bool
    auto_duo_code_review_enabled: str
    autoclose_referenced_issues: bool
    avatar_url: str
    build_git_strategy: str
    build_timeout: int
    builds_access_level: str
    can_create_merge_request_in: bool
    ci_allow_fork_pipelines_to_run_in_parent_project: bool
    ci_config_path: str
    ci_default_git_depth: int
    ci_delete_pipelines_in_seconds: int
    ci_forward_deployment_enabled: bool
    ci_forward_deployment_rollback_allowed: bool
    ci_id_token_sub_claim_components: list
    ci_job_token_scope_enabled: bool
    ci_pipeline_variables_minimum_override_role: str
    ci_push_repository_for_job_token_allowed: bool
    ci_restrict_pipeline_cancellation_role: str
    ci_separated_caches: bool
    compliance_frameworks: str
    container_expiration_policy: dict
    container_registry_access_level: str
    container_registry_enabled: bool
    container_registry_image_prefix: str
    created_at: str
    creator_id: int
    custom_attributes: dict
    default_branch: str
    description: str
    description_html: str
    duo_remote_flows_enabled: str
    emails_disabled: bool
    emails_enabled: bool
    empty_repo: bool
    enforce_auth_checks_on_uploads: bool
    environments_access_level: str
    external_authorization_classification_label: str
    feature_flags_access_level: str
    forked_from_project: dict
    forking_access_level: str
    forks_count: int
    group_runners_enabled: bool
    http_url_to_repo: str
    id: int
    import_error: str
    import_status: str
    import_type: str
    import_url: str
    infrastructure_access_level: str
    issue_branch_template: str
    issues_access_level: str
    issues_enabled: bool
    issues_template: str
    jobs_enabled: bool
    keep_latest_artifact: bool
    last_activity_at: str
    lfs_enabled: bool
    license: dict
    license_url: str
    links: dict
    marked_for_deletion_at: str
    marked_for_deletion_on: str
    max_artifacts_size: int
    merge_commit_template: str
    merge_method: str
    merge_pipelines_enabled: str
    merge_request_title_regex: str
    merge_request_title_regex_description: str
    merge_requests_access_level: str
    merge_requests_enabled: bool
    merge_requests_template: str
    merge_trains_enabled: str
    merge_trains_skip_train_allowed: str
    mirror: str
    mirror_overwrites_diverged_branches: str
    mirror_trigger_builds: str
    mirror_user_id: str
    model_experiments_access_level: str
    model_registry_access_level: str
    monitor_access_level: str
    mr_default_target_self: bool
    name: str
    name_with_namespace: str
    namespace: dict
    only_allow_merge_if_all_discussions_are_resolved: bool
    only_allow_merge_if_all_status_checks_passed: str
    only_allow_merge_if_pipeline_succeeds: bool
    only_mirror_protected_branches: str
    open_issues_count: int
    owner: dict
    package_registry_access_level: str
    packages_enabled: bool
    pages_access_level: str
    path: str
    path_with_namespace: str
    permissions: dict
    pre_receive_secret_detection_enabled: bool
    prevent_merge_without_jira_issue: str
    printing_merge_request_link_enabled: bool
    public_jobs: bool
    readme_url: str
    releases_access_level: str
    remove_source_branch_after_merge: bool
    repository_access_level: str
    repository_object_format: str
    repository_storage: str
    request_access_enabled: bool
    requirements_access_level: str
    requirements_enabled: str
    resolve_outdated_diff_discussions: bool
    resource_group_default_process_mode: str
    restrict_user_defined_variables: bool
    runner_token_expiration_interval: int
    runners_token: str
    secret_push_protection_enabled: bool
    security_and_compliance_access_level: str
    security_and_compliance_enabled: str
    service_desk_address: str
    service_desk_enabled: bool
    shared_runners_enabled: bool
    shared_with_groups: list
    show_diff_preview_in_email: bool
    snippets_access_level: str
    snippets_enabled: bool
    spp_repository_pipeline_access: bool
    squash_commit_template: str
    squash_option: str
    ssh_url_to_repo: str
    star_count: int
    statistics: dict
    suggestion_commit_message: str
    tag_list: list
    topics: list
    updated_at: str
    visibility: str
    warn_about_potentially_unwanted_characters: bool
    web_based_commit_signing_enabled: str
    web_url: str
    wiki_access_level: str
    wiki_enabled: bool


class ApiEntitiesProjectWithAccessLoadMatch(TypedDict):
    id: str


class Project(TypedDict, total=False):
    allow_merge_on_skipped_pipeline: bool
    allow_pipeline_trigger_approve_deployment: bool
    analytics_access_level: str
    approvals_before_merge: str
    archived: bool
    auto_cancel_pending_pipelines: str
    auto_devops_deploy_strategy: str
    auto_devops_enabled: bool
    auto_duo_code_review_enabled: str
    autoclose_referenced_issues: bool
    avatar_url: str
    build_git_strategy: str
    build_timeout: int
    builds_access_level: str
    can_create_merge_request_in: bool
    ci_allow_fork_pipelines_to_run_in_parent_project: bool
    ci_config_path: str
    ci_default_git_depth: int
    ci_delete_pipelines_in_seconds: int
    ci_forward_deployment_enabled: bool
    ci_forward_deployment_rollback_allowed: bool
    ci_id_token_sub_claim_components: list
    ci_job_token_scope_enabled: bool
    ci_pipeline_variables_minimum_override_role: str
    ci_push_repository_for_job_token_allowed: bool
    ci_restrict_pipeline_cancellation_role: str
    ci_separated_caches: bool
    compliance_frameworks: str
    container_expiration_policy: dict
    container_registry_access_level: str
    container_registry_enabled: bool
    container_registry_image_prefix: str
    created_at: str
    creator_id: int
    custom_attributes: dict
    default_branch: str
    description: str
    description_html: str
    duo_remote_flows_enabled: str
    emails_disabled: bool
    emails_enabled: bool
    empty_repo: bool
    enforce_auth_checks_on_uploads: bool
    environments_access_level: str
    external_authorization_classification_label: str
    feature_flags_access_level: str
    forked_from_project: dict
    forking_access_level: str
    forks_count: int
    group_runners_enabled: bool
    http_url_to_repo: str
    id: int
    import_error: str
    import_status: str
    import_type: str
    import_url: str
    infrastructure_access_level: str
    issue_branch_template: str
    issues_access_level: str
    issues_enabled: bool
    issues_template: str
    jobs_enabled: bool
    keep_latest_artifact: bool
    last_activity_at: str
    lfs_enabled: bool
    license: dict
    license_url: str
    links: dict
    marked_for_deletion_at: str
    marked_for_deletion_on: str
    max_artifacts_size: int
    merge_commit_template: str
    merge_method: str
    merge_pipelines_enabled: str
    merge_request_title_regex: str
    merge_request_title_regex_description: str
    merge_requests_access_level: str
    merge_requests_enabled: bool
    merge_requests_template: str
    merge_trains_enabled: str
    merge_trains_skip_train_allowed: str
    mirror: str
    mirror_overwrites_diverged_branches: str
    mirror_trigger_builds: str
    mirror_user_id: str
    model_experiments_access_level: str
    model_registry_access_level: str
    monitor_access_level: str
    mr_default_target_self: bool
    name: str
    name_with_namespace: str
    namespace: dict
    only_allow_merge_if_all_discussions_are_resolved: bool
    only_allow_merge_if_all_status_checks_passed: str
    only_allow_merge_if_pipeline_succeeds: bool
    only_mirror_protected_branches: str
    open_issues_count: int
    owner: dict
    package_registry_access_level: str
    packages_enabled: bool
    pages_access_level: str
    path: str
    path_with_namespace: str
    pre_receive_secret_detection_enabled: bool
    prevent_merge_without_jira_issue: str
    printing_merge_request_link_enabled: bool
    public_jobs: bool
    readme_url: str
    releases_access_level: str
    remove_source_branch_after_merge: bool
    repository_access_level: str
    repository_object_format: str
    repository_storage: str
    request_access_enabled: bool
    requirements_access_level: str
    requirements_enabled: str
    resolve_outdated_diff_discussions: bool
    resource_group_default_process_mode: str
    restrict_user_defined_variables: bool
    runner_token_expiration_interval: int
    runners_token: str
    secret_push_protection_enabled: bool
    security_and_compliance_access_level: str
    security_and_compliance_enabled: str
    service_desk_address: str
    service_desk_enabled: bool
    shared_runners_enabled: bool
    shared_with_groups: list
    show_diff_preview_in_email: bool
    snippets_access_level: str
    snippets_enabled: bool
    spp_repository_pipeline_access: bool
    squash_commit_template: str
    squash_option: str
    ssh_url_to_repo: str
    star_count: int
    statistics: dict
    suggestion_commit_message: str
    tag_list: list
    topics: list
    updated_at: str
    visibility: str
    warn_about_potentially_unwanted_characters: bool
    web_based_commit_signing_enabled: str
    web_url: str
    wiki_access_level: str
    wiki_enabled: bool


class ProjectListMatch(TypedDict, total=False):
    allow_merge_on_skipped_pipeline: bool
    allow_pipeline_trigger_approve_deployment: bool
    analytics_access_level: str
    approvals_before_merge: str
    archived: bool
    auto_cancel_pending_pipelines: str
    auto_devops_deploy_strategy: str
    auto_devops_enabled: bool
    auto_duo_code_review_enabled: str
    autoclose_referenced_issues: bool
    avatar_url: str
    build_git_strategy: str
    build_timeout: int
    builds_access_level: str
    can_create_merge_request_in: bool
    ci_allow_fork_pipelines_to_run_in_parent_project: bool
    ci_config_path: str
    ci_default_git_depth: int
    ci_delete_pipelines_in_seconds: int
    ci_forward_deployment_enabled: bool
    ci_forward_deployment_rollback_allowed: bool
    ci_id_token_sub_claim_components: list
    ci_job_token_scope_enabled: bool
    ci_pipeline_variables_minimum_override_role: str
    ci_push_repository_for_job_token_allowed: bool
    ci_restrict_pipeline_cancellation_role: str
    ci_separated_caches: bool
    compliance_frameworks: str
    container_expiration_policy: dict
    container_registry_access_level: str
    container_registry_enabled: bool
    container_registry_image_prefix: str
    created_at: str
    creator_id: int
    custom_attributes: dict
    default_branch: str
    description: str
    description_html: str
    duo_remote_flows_enabled: str
    emails_disabled: bool
    emails_enabled: bool
    empty_repo: bool
    enforce_auth_checks_on_uploads: bool
    environments_access_level: str
    external_authorization_classification_label: str
    feature_flags_access_level: str
    forked_from_project: dict
    forking_access_level: str
    forks_count: int
    group_runners_enabled: bool
    http_url_to_repo: str
    id: int
    import_error: str
    import_status: str
    import_type: str
    import_url: str
    infrastructure_access_level: str
    issue_branch_template: str
    issues_access_level: str
    issues_enabled: bool
    issues_template: str
    jobs_enabled: bool
    keep_latest_artifact: bool
    last_activity_at: str
    lfs_enabled: bool
    license: dict
    license_url: str
    links: dict
    marked_for_deletion_at: str
    marked_for_deletion_on: str
    max_artifacts_size: int
    merge_commit_template: str
    merge_method: str
    merge_pipelines_enabled: str
    merge_request_title_regex: str
    merge_request_title_regex_description: str
    merge_requests_access_level: str
    merge_requests_enabled: bool
    merge_requests_template: str
    merge_trains_enabled: str
    merge_trains_skip_train_allowed: str
    mirror: str
    mirror_overwrites_diverged_branches: str
    mirror_trigger_builds: str
    mirror_user_id: str
    model_experiments_access_level: str
    model_registry_access_level: str
    monitor_access_level: str
    mr_default_target_self: bool
    name: str
    name_with_namespace: str
    namespace: dict
    only_allow_merge_if_all_discussions_are_resolved: bool
    only_allow_merge_if_all_status_checks_passed: str
    only_allow_merge_if_pipeline_succeeds: bool
    only_mirror_protected_branches: str
    open_issues_count: int
    owner: dict
    package_registry_access_level: str
    packages_enabled: bool
    pages_access_level: str
    path: str
    path_with_namespace: str
    pre_receive_secret_detection_enabled: bool
    prevent_merge_without_jira_issue: str
    printing_merge_request_link_enabled: bool
    public_jobs: bool
    readme_url: str
    releases_access_level: str
    remove_source_branch_after_merge: bool
    repository_access_level: str
    repository_object_format: str
    repository_storage: str
    request_access_enabled: bool
    requirements_access_level: str
    requirements_enabled: str
    resolve_outdated_diff_discussions: bool
    resource_group_default_process_mode: str
    restrict_user_defined_variables: bool
    runner_token_expiration_interval: int
    runners_token: str
    secret_push_protection_enabled: bool
    security_and_compliance_access_level: str
    security_and_compliance_enabled: str
    service_desk_address: str
    service_desk_enabled: bool
    shared_runners_enabled: bool
    shared_with_groups: list
    show_diff_preview_in_email: bool
    snippets_access_level: str
    snippets_enabled: bool
    spp_repository_pipeline_access: bool
    squash_commit_template: str
    squash_option: str
    ssh_url_to_repo: str
    star_count: int
    statistics: dict
    suggestion_commit_message: str
    tag_list: list
    topics: list
    updated_at: str
    visibility: str
    warn_about_potentially_unwanted_characters: bool
    web_based_commit_signing_enabled: str
    web_url: str
    wiki_access_level: str
    wiki_enabled: bool


class ProjectCreateData(TypedDict, total=False):
    allow_merge_on_skipped_pipeline: bool
    allow_pipeline_trigger_approve_deployment: bool
    analytics_access_level: str
    approvals_before_merge: str
    archived: bool
    auto_cancel_pending_pipelines: str
    auto_devops_deploy_strategy: str
    auto_devops_enabled: bool
    auto_duo_code_review_enabled: str
    autoclose_referenced_issues: bool
    avatar_url: str
    build_git_strategy: str
    build_timeout: int
    builds_access_level: str
    can_create_merge_request_in: bool
    ci_allow_fork_pipelines_to_run_in_parent_project: bool
    ci_config_path: str
    ci_default_git_depth: int
    ci_delete_pipelines_in_seconds: int
    ci_forward_deployment_enabled: bool
    ci_forward_deployment_rollback_allowed: bool
    ci_id_token_sub_claim_components: list
    ci_job_token_scope_enabled: bool
    ci_pipeline_variables_minimum_override_role: str
    ci_push_repository_for_job_token_allowed: bool
    ci_restrict_pipeline_cancellation_role: str
    ci_separated_caches: bool
    compliance_frameworks: str
    container_expiration_policy: dict
    container_registry_access_level: str
    container_registry_enabled: bool
    container_registry_image_prefix: str
    created_at: str
    creator_id: int
    custom_attributes: dict
    default_branch: str
    description: str
    description_html: str
    duo_remote_flows_enabled: str
    emails_disabled: bool
    emails_enabled: bool
    empty_repo: bool
    enforce_auth_checks_on_uploads: bool
    environments_access_level: str
    external_authorization_classification_label: str
    feature_flags_access_level: str
    forked_from_project: dict
    forking_access_level: str
    forks_count: int
    group_runners_enabled: bool
    http_url_to_repo: str
    id: int
    import_error: str
    import_status: str
    import_type: str
    import_url: str
    infrastructure_access_level: str
    issue_branch_template: str
    issues_access_level: str
    issues_enabled: bool
    issues_template: str
    jobs_enabled: bool
    keep_latest_artifact: bool
    last_activity_at: str
    lfs_enabled: bool
    license: dict
    license_url: str
    links: dict
    marked_for_deletion_at: str
    marked_for_deletion_on: str
    max_artifacts_size: int
    merge_commit_template: str
    merge_method: str
    merge_pipelines_enabled: str
    merge_request_title_regex: str
    merge_request_title_regex_description: str
    merge_requests_access_level: str
    merge_requests_enabled: bool
    merge_requests_template: str
    merge_trains_enabled: str
    merge_trains_skip_train_allowed: str
    mirror: str
    mirror_overwrites_diverged_branches: str
    mirror_trigger_builds: str
    mirror_user_id: str
    model_experiments_access_level: str
    model_registry_access_level: str
    monitor_access_level: str
    mr_default_target_self: bool
    name: str
    name_with_namespace: str
    namespace: dict
    only_allow_merge_if_all_discussions_are_resolved: bool
    only_allow_merge_if_all_status_checks_passed: str
    only_allow_merge_if_pipeline_succeeds: bool
    only_mirror_protected_branches: str
    open_issues_count: int
    owner: dict
    package_registry_access_level: str
    packages_enabled: bool
    pages_access_level: str
    path: str
    path_with_namespace: str
    pre_receive_secret_detection_enabled: bool
    prevent_merge_without_jira_issue: str
    printing_merge_request_link_enabled: bool
    public_jobs: bool
    readme_url: str
    releases_access_level: str
    remove_source_branch_after_merge: bool
    repository_access_level: str
    repository_object_format: str
    repository_storage: str
    request_access_enabled: bool
    requirements_access_level: str
    requirements_enabled: str
    resolve_outdated_diff_discussions: bool
    resource_group_default_process_mode: str
    restrict_user_defined_variables: bool
    runner_token_expiration_interval: int
    runners_token: str
    secret_push_protection_enabled: bool
    security_and_compliance_access_level: str
    security_and_compliance_enabled: str
    service_desk_address: str
    service_desk_enabled: bool
    shared_runners_enabled: bool
    shared_with_groups: list
    show_diff_preview_in_email: bool
    snippets_access_level: str
    snippets_enabled: bool
    spp_repository_pipeline_access: bool
    squash_commit_template: str
    squash_option: str
    ssh_url_to_repo: str
    star_count: int
    statistics: dict
    suggestion_commit_message: str
    tag_list: list
    topics: list
    updated_at: str
    visibility: str
    warn_about_potentially_unwanted_characters: bool
    web_based_commit_signing_enabled: str
    web_url: str
    wiki_access_level: str
    wiki_enabled: bool


class ProjectUpdateDataRequired(TypedDict):
    id: str


class ProjectUpdateData(ProjectUpdateDataRequired, total=False):
    allow_merge_on_skipped_pipeline: bool
    allow_pipeline_trigger_approve_deployment: bool
    analytics_access_level: str
    approvals_before_merge: str
    archived: bool
    auto_cancel_pending_pipelines: str
    auto_devops_deploy_strategy: str
    auto_devops_enabled: bool
    auto_duo_code_review_enabled: str
    autoclose_referenced_issues: bool
    avatar_url: str
    build_git_strategy: str
    build_timeout: int
    builds_access_level: str
    can_create_merge_request_in: bool
    ci_allow_fork_pipelines_to_run_in_parent_project: bool
    ci_config_path: str
    ci_default_git_depth: int
    ci_delete_pipelines_in_seconds: int
    ci_forward_deployment_enabled: bool
    ci_forward_deployment_rollback_allowed: bool
    ci_id_token_sub_claim_components: list
    ci_job_token_scope_enabled: bool
    ci_pipeline_variables_minimum_override_role: str
    ci_push_repository_for_job_token_allowed: bool
    ci_restrict_pipeline_cancellation_role: str
    ci_separated_caches: bool
    compliance_frameworks: str
    container_expiration_policy: dict
    container_registry_access_level: str
    container_registry_enabled: bool
    container_registry_image_prefix: str
    created_at: str
    creator_id: int
    custom_attributes: dict
    default_branch: str
    description: str
    description_html: str
    duo_remote_flows_enabled: str
    emails_disabled: bool
    emails_enabled: bool
    empty_repo: bool
    enforce_auth_checks_on_uploads: bool
    environments_access_level: str
    external_authorization_classification_label: str
    feature_flags_access_level: str
    forked_from_project: dict
    forking_access_level: str
    forks_count: int
    group_runners_enabled: bool
    http_url_to_repo: str
    import_error: str
    import_status: str
    import_type: str
    import_url: str
    infrastructure_access_level: str
    issue_branch_template: str
    issues_access_level: str
    issues_enabled: bool
    issues_template: str
    jobs_enabled: bool
    keep_latest_artifact: bool
    last_activity_at: str
    lfs_enabled: bool
    license: dict
    license_url: str
    links: dict
    marked_for_deletion_at: str
    marked_for_deletion_on: str
    max_artifacts_size: int
    merge_commit_template: str
    merge_method: str
    merge_pipelines_enabled: str
    merge_request_title_regex: str
    merge_request_title_regex_description: str
    merge_requests_access_level: str
    merge_requests_enabled: bool
    merge_requests_template: str
    merge_trains_enabled: str
    merge_trains_skip_train_allowed: str
    mirror: str
    mirror_overwrites_diverged_branches: str
    mirror_trigger_builds: str
    mirror_user_id: str
    model_experiments_access_level: str
    model_registry_access_level: str
    monitor_access_level: str
    mr_default_target_self: bool
    name: str
    name_with_namespace: str
    namespace: dict
    only_allow_merge_if_all_discussions_are_resolved: bool
    only_allow_merge_if_all_status_checks_passed: str
    only_allow_merge_if_pipeline_succeeds: bool
    only_mirror_protected_branches: str
    open_issues_count: int
    owner: dict
    package_registry_access_level: str
    packages_enabled: bool
    pages_access_level: str
    path: str
    path_with_namespace: str
    pre_receive_secret_detection_enabled: bool
    prevent_merge_without_jira_issue: str
    printing_merge_request_link_enabled: bool
    public_jobs: bool
    readme_url: str
    releases_access_level: str
    remove_source_branch_after_merge: bool
    repository_access_level: str
    repository_object_format: str
    repository_storage: str
    request_access_enabled: bool
    requirements_access_level: str
    requirements_enabled: str
    resolve_outdated_diff_discussions: bool
    resource_group_default_process_mode: str
    restrict_user_defined_variables: bool
    runner_token_expiration_interval: int
    runners_token: str
    secret_push_protection_enabled: bool
    security_and_compliance_access_level: str
    security_and_compliance_enabled: str
    service_desk_address: str
    service_desk_enabled: bool
    shared_runners_enabled: bool
    shared_with_groups: list
    show_diff_preview_in_email: bool
    snippets_access_level: str
    snippets_enabled: bool
    spp_repository_pipeline_access: bool
    squash_commit_template: str
    squash_option: str
    ssh_url_to_repo: str
    star_count: int
    statistics: dict
    suggestion_commit_message: str
    tag_list: list
    topics: list
    updated_at: str
    visibility: str
    warn_about_potentially_unwanted_characters: bool
    web_based_commit_signing_enabled: str
    web_url: str
    wiki_access_level: str
    wiki_enabled: bool


class ProjectRemoveMatch(TypedDict):
    id: str
