// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/aql-lang/aql/eng/go"
	sdk "github.com/voxgig-sdk/gitlab-sdk/go"
)

// registerSDKWords installs three native AQL words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word.
func registerSDKWords(r *eng.Registry, client *sdk.GitlabSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.NativeSig{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		dual := eng.NativeSig{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:        op,
			ForwardArgs: true,
			Signatures:  []eng.NativeSig{single, dual},
		})
	}
}

func runOp(client *sdk.GitlabSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.GitlabSDK, name string) (sdk.GitlabEntity, error) {
	switch strings.ToLower(name) {
	case "access_request":
		return client.AccessRequest(nil), nil
	case "alert_management":
		return client.AlertManagement(nil), nil
	case "api_entities_access_requester":
		return client.ApiEntitiesAccessRequester(nil), nil
	case "api_entities_appearance":
		return client.ApiEntitiesAppearance(nil), nil
	case "api_entities_application":
		return client.ApiEntitiesApplication(nil), nil
	case "api_entities_application_statistic":
		return client.ApiEntitiesApplicationStatistic(nil), nil
	case "api_entities_application_with_secret":
		return client.ApiEntitiesApplicationWithSecret(nil), nil
	case "api_entities_avatar":
		return client.ApiEntitiesAvatar(nil), nil
	case "api_entities_award_emoji":
		return client.ApiEntitiesAwardEmoji(nil), nil
	case "api_entities_badge":
		return client.ApiEntitiesBadge(nil), nil
	case "api_entities_basic_badge_detail":
		return client.ApiEntitiesBasicBadgeDetail(nil), nil
	case "api_entities_basic_group_detail":
		return client.ApiEntitiesBasicGroupDetail(nil), nil
	case "api_entities_basic_project_detail":
		return client.ApiEntitiesBasicProjectDetail(nil), nil
	case "api_entities_basic_ref":
		return client.ApiEntitiesBasicRef(nil), nil
	case "api_entities_basic_success":
		return client.ApiEntitiesBasicSuccess(nil), nil
	case "api_entities_batched_background_migration":
		return client.ApiEntitiesBatchedBackgroundMigration(nil), nil
	case "api_entities_branch":
		return client.ApiEntitiesBranch(nil), nil
	case "api_entities_bulk_import":
		return client.ApiEntitiesBulkImport(nil), nil
	case "api_entities_bulk_imports_entity_failure":
		return client.ApiEntitiesBulkImportsEntityFailure(nil), nil
	case "api_entities_bulk_imports_export_status":
		return client.ApiEntitiesBulkImportsExportStatus(nil), nil
	case "api_entities_changelog":
		return client.ApiEntitiesChangelog(nil), nil
	case "api_entities_ci_bridge":
		return client.ApiEntitiesCiBridge(nil), nil
	case "api_entities_ci_catalog_resources_version":
		return client.ApiEntitiesCiCatalogResourcesVersion(nil), nil
	case "api_entities_ci_job":
		return client.ApiEntitiesCiJob(nil), nil
	case "api_entities_ci_job_basic":
		return client.ApiEntitiesCiJobBasic(nil), nil
	case "api_entities_ci_job_basic_with_project":
		return client.ApiEntitiesCiJobBasicWithProject(nil), nil
	case "api_entities_ci_lint_result":
		return client.ApiEntitiesCiLintResult(nil), nil
	case "api_entities_ci_pipeline":
		return client.ApiEntitiesCiPipeline(nil), nil
	case "api_entities_ci_pipeline_basic":
		return client.ApiEntitiesCiPipelineBasic(nil), nil
	case "api_entities_ci_pipeline_schedule":
		return client.ApiEntitiesCiPipelineSchedule(nil), nil
	case "api_entities_ci_pipeline_schedule_detail":
		return client.ApiEntitiesCiPipelineScheduleDetail(nil), nil
	case "api_entities_ci_reset_token_result":
		return client.ApiEntitiesCiResetTokenResult(nil), nil
	case "api_entities_ci_resource_group":
		return client.ApiEntitiesCiResourceGroup(nil), nil
	case "api_entities_ci_runner":
		return client.ApiEntitiesCiRunner(nil), nil
	case "api_entities_ci_runner_detail":
		return client.ApiEntitiesCiRunnerDetail(nil), nil
	case "api_entities_ci_runner_manager":
		return client.ApiEntitiesCiRunnerManager(nil), nil
	case "api_entities_ci_runner_registration_detail":
		return client.ApiEntitiesCiRunnerRegistrationDetail(nil), nil
	case "api_entities_ci_secure_file":
		return client.ApiEntitiesCiSecureFile(nil), nil
	case "api_entities_ci_variable":
		return client.ApiEntitiesCiVariable(nil), nil
	case "api_entities_cluster":
		return client.ApiEntitiesCluster(nil), nil
	case "api_entities_cluster_group":
		return client.ApiEntitiesClusterGroup(nil), nil
	case "api_entities_cluster_project":
		return client.ApiEntitiesClusterProject(nil), nil
	case "api_entities_clusters_agent":
		return client.ApiEntitiesClustersAgent(nil), nil
	case "api_entities_clusters_agent_token":
		return client.ApiEntitiesClustersAgentToken(nil), nil
	case "api_entities_clusters_agent_token_basic":
		return client.ApiEntitiesClustersAgentTokenBasic(nil), nil
	case "api_entities_clusters_agent_token_with_token":
		return client.ApiEntitiesClustersAgentTokenWithToken(nil), nil
	case "api_entities_commit":
		return client.ApiEntitiesCommit(nil), nil
	case "api_entities_commit_detail":
		return client.ApiEntitiesCommitDetail(nil), nil
	case "api_entities_commit_note":
		return client.ApiEntitiesCommitNote(nil), nil
	case "api_entities_commit_sequence":
		return client.ApiEntitiesCommitSequence(nil), nil
	case "api_entities_commit_signature":
		return client.ApiEntitiesCommitSignature(nil), nil
	case "api_entities_commit_status":
		return client.ApiEntitiesCommitStatus(nil), nil
	case "api_entities_compare":
		return client.ApiEntitiesCompare(nil), nil
	case "api_entities_container_registry_repository":
		return client.ApiEntitiesContainerRegistryRepository(nil), nil
	case "api_entities_container_registry_tag":
		return client.ApiEntitiesContainerRegistryTag(nil), nil
	case "api_entities_container_registry_tag_detail":
		return client.ApiEntitiesContainerRegistryTagDetail(nil), nil
	case "api_entities_contributor":
		return client.ApiEntitiesContributor(nil), nil
	case "api_entities_deploy_key":
		return client.ApiEntitiesDeployKey(nil), nil
	case "api_entities_deploy_keys_project":
		return client.ApiEntitiesDeployKeysProject(nil), nil
	case "api_entities_deploy_token":
		return client.ApiEntitiesDeployToken(nil), nil
	case "api_entities_deploy_token_with_token":
		return client.ApiEntitiesDeployTokenWithToken(nil), nil
	case "api_entities_deployment":
		return client.ApiEntitiesDeployment(nil), nil
	case "api_entities_deployment_extended":
		return client.ApiEntitiesDeploymentExtended(nil), nil
	case "api_entities_deployments_approval":
		return client.ApiEntitiesDeploymentsApproval(nil), nil
	case "api_entities_dictionary_table":
		return client.ApiEntitiesDictionaryTable(nil), nil
	case "api_entities_diff":
		return client.ApiEntitiesDiff(nil), nil
	case "api_entities_discovered_cluster":
		return client.ApiEntitiesDiscoveredCluster(nil), nil
	case "api_entities_draft_note":
		return client.ApiEntitiesDraftNote(nil), nil
	case "api_entities_environment":
		return client.ApiEntitiesEnvironment(nil), nil
	case "api_entities_error_tracking_client_key":
		return client.ApiEntitiesErrorTrackingClientKey(nil), nil
	case "api_entities_error_tracking_project_setting":
		return client.ApiEntitiesErrorTrackingProjectSetting(nil), nil
	case "api_entities_event":
		return client.ApiEntitiesEvent(nil), nil
	case "api_entities_feature":
		return client.ApiEntitiesFeature(nil), nil
	case "api_entities_feature_definition":
		return client.ApiEntitiesFeatureDefinition(nil), nil
	case "api_entities_feature_flag":
		return client.ApiEntitiesFeatureFlag(nil), nil
	case "api_entities_feature_flag_user_list":
		return client.ApiEntitiesFeatureFlagUserList(nil), nil
	case "api_entities_freeze_period":
		return client.ApiEntitiesFreezePeriod(nil), nil
	case "api_entities_gitlab_subscription":
		return client.ApiEntitiesGitlabSubscription(nil), nil
	case "api_entities_go_module_version":
		return client.ApiEntitiesGoModuleVersion(nil), nil
	case "api_entities_group":
		return client.ApiEntitiesGroup(nil), nil
	case "api_entities_group_detail":
		return client.ApiEntitiesGroupDetail(nil), nil
	case "api_entities_hook":
		return client.ApiEntitiesHook(nil), nil
	case "api_entities_integration":
		return client.ApiEntitiesIntegration(nil), nil
	case "api_entities_integration_basic":
		return client.ApiEntitiesIntegrationBasic(nil), nil
	case "api_entities_invitation":
		return client.ApiEntitiesInvitation(nil), nil
	case "api_entities_issuable_time_stat":
		return client.ApiEntitiesIssuableTimeStat(nil), nil
	case "api_entities_issue":
		return client.ApiEntitiesIssue(nil), nil
	case "api_entities_issue_link":
		return client.ApiEntitiesIssueLink(nil), nil
	case "api_entities_license":
		return client.ApiEntitiesLicense(nil), nil
	case "api_entities_markdown":
		return client.ApiEntitiesMarkdown(nil), nil
	case "api_entities_markdown_upload_admin":
		return client.ApiEntitiesMarkdownUploadAdmin(nil), nil
	case "api_entities_member":
		return client.ApiEntitiesMember(nil), nil
	case "api_entities_merge":
		return client.ApiEntitiesMerge(nil), nil
	case "api_entities_merge_request_approval":
		return client.ApiEntitiesMergeRequestApproval(nil), nil
	case "api_entities_merge_request_basic":
		return client.ApiEntitiesMergeRequestBasic(nil), nil
	case "api_entities_merge_request_change":
		return client.ApiEntitiesMergeRequestChange(nil), nil
	case "api_entities_merge_request_diff":
		return client.ApiEntitiesMergeRequestDiff(nil), nil
	case "api_entities_merge_request_diff_full":
		return client.ApiEntitiesMergeRequestDiffFull(nil), nil
	case "api_entities_merge_request_reviewer":
		return client.ApiEntitiesMergeRequestReviewer(nil), nil
	case "api_entities_metric_image":
		return client.ApiEntitiesMetricImage(nil), nil
	case "api_entities_mr_note":
		return client.ApiEntitiesMrNote(nil), nil
	case "api_entities_namespace":
		return client.ApiEntitiesNamespace(nil), nil
	case "api_entities_namespace_existence":
		return client.ApiEntitiesNamespaceExistence(nil), nil
	case "api_entities_namespaces_storage_limit_exclusion":
		return client.ApiEntitiesNamespacesStorageLimitExclusion(nil), nil
	case "api_entities_npm_package":
		return client.ApiEntitiesNpmPackage(nil), nil
	case "api_entities_npm_package_tag":
		return client.ApiEntitiesNpmPackageTag(nil), nil
	case "api_entities_nuget_packages_version":
		return client.ApiEntitiesNugetPackagesVersion(nil), nil
	case "api_entities_nuget_search_result":
		return client.ApiEntitiesNugetSearchResult(nil), nil
	case "api_entities_nuget_service_index":
		return client.ApiEntitiesNugetServiceIndex(nil), nil
	case "api_entities_organizations_organization":
		return client.ApiEntitiesOrganizationsOrganization(nil), nil
	case "api_entities_package":
		return client.ApiEntitiesPackage(nil), nil
	case "api_entities_package_file":
		return client.ApiEntitiesPackageFile(nil), nil
	case "api_entities_package_pipeline":
		return client.ApiEntitiesPackagePipeline(nil), nil
	case "api_entities_packages_conan_files_list":
		return client.ApiEntitiesPackagesConanFilesList(nil), nil
	case "api_entities_packages_conan_package_manifest":
		return client.ApiEntitiesPackagesConanPackageManifest(nil), nil
	case "api_entities_packages_conan_package_revision":
		return client.ApiEntitiesPackagesConanPackageRevision(nil), nil
	case "api_entities_packages_conan_package_snapshot":
		return client.ApiEntitiesPackagesConanPackageSnapshot(nil), nil
	case "api_entities_packages_conan_recipe_manifest":
		return client.ApiEntitiesPackagesConanRecipeManifest(nil), nil
	case "api_entities_packages_conan_recipe_revision":
		return client.ApiEntitiesPackagesConanRecipeRevision(nil), nil
	case "api_entities_packages_conan_recipe_snapshot":
		return client.ApiEntitiesPackagesConanRecipeSnapshot(nil), nil
	case "api_entities_packages_conan_revision":
		return client.ApiEntitiesPackagesConanRevision(nil), nil
	case "api_entities_packages_conan_upload_url":
		return client.ApiEntitiesPackagesConanUploadUrl(nil), nil
	case "api_entities_packages_debian_distribution":
		return client.ApiEntitiesPackagesDebianDistribution(nil), nil
	case "api_entities_pages_domain":
		return client.ApiEntitiesPagesDomain(nil), nil
	case "api_entities_pages_domain_basic":
		return client.ApiEntitiesPagesDomainBasic(nil), nil
	case "api_entities_personal_access_token":
		return client.ApiEntitiesPersonalAccessToken(nil), nil
	case "api_entities_personal_access_token_with_last_used_ip":
		return client.ApiEntitiesPersonalAccessTokenWithLastUsedIp(nil), nil
	case "api_entities_personal_access_token_with_token":
		return client.ApiEntitiesPersonalAccessTokenWithToken(nil), nil
	case "api_entities_personal_snippet":
		return client.ApiEntitiesPersonalSnippet(nil), nil
	case "api_entities_plan_limit":
		return client.ApiEntitiesPlanLimit(nil), nil
	case "api_entities_project":
		return client.ApiEntitiesProject(nil), nil
	case "api_entities_project_daily_statistic":
		return client.ApiEntitiesProjectDailyStatistic(nil), nil
	case "api_entities_project_export_status":
		return client.ApiEntitiesProjectExportStatus(nil), nil
	case "api_entities_project_group_link":
		return client.ApiEntitiesProjectGroupLink(nil), nil
	case "api_entities_project_hook":
		return client.ApiEntitiesProjectHook(nil), nil
	case "api_entities_project_import_status":
		return client.ApiEntitiesProjectImportStatus(nil), nil
	case "api_entities_project_job_token_scope":
		return client.ApiEntitiesProjectJobTokenScope(nil), nil
	case "api_entities_project_repository_storage":
		return client.ApiEntitiesProjectRepositoryStorage(nil), nil
	case "api_entities_project_snippet":
		return client.ApiEntitiesProjectSnippet(nil), nil
	case "api_entities_project_upload":
		return client.ApiEntitiesProjectUpload(nil), nil
	case "api_entities_project_with_access":
		return client.ApiEntitiesProjectWithAccess(nil), nil
	case "api_entities_projects_container_registry_protection_rule":
		return client.ApiEntitiesProjectsContainerRegistryProtectionRule(nil), nil
	case "api_entities_projects_packages_protection_rule":
		return client.ApiEntitiesProjectsPackagesProtectionRule(nil), nil
	case "api_entities_projects_topic":
		return client.ApiEntitiesProjectsTopic(nil), nil
	case "api_entities_protected_branch":
		return client.ApiEntitiesProtectedBranch(nil), nil
	case "api_entities_protected_tag":
		return client.ApiEntitiesProtectedTag(nil), nil
	case "api_entities_public_group_detail":
		return client.ApiEntitiesPublicGroupDetail(nil), nil
	case "api_entities_related_issue":
		return client.ApiEntitiesRelatedIssue(nil), nil
	case "api_entities_relation_import_tracker":
		return client.ApiEntitiesRelationImportTracker(nil), nil
	case "api_entities_release":
		return client.ApiEntitiesRelease(nil), nil
	case "api_entities_releases_link":
		return client.ApiEntitiesReleasesLink(nil), nil
	case "api_entities_remote_mirror":
		return client.ApiEntitiesRemoteMirror(nil), nil
	case "api_entities_repository_health":
		return client.ApiEntitiesRepositoryHealth(nil), nil
	case "api_entities_resource_access_token_with_token":
		return client.ApiEntitiesResourceAccessTokenWithToken(nil), nil
	case "api_entities_resource_milestone_event":
		return client.ApiEntitiesResourceMilestoneEvent(nil), nil
	case "api_entities_snippet":
		return client.ApiEntitiesSnippet(nil), nil
	case "api_entities_ssh_key_with_user":
		return client.ApiEntitiesSshKeyWithUser(nil), nil
	case "api_entities_suggestion":
		return client.ApiEntitiesSuggestion(nil), nil
	case "api_entities_system_broadcast_message":
		return client.ApiEntitiesSystemBroadcastMessage(nil), nil
	case "api_entities_tag":
		return client.ApiEntitiesTag(nil), nil
	case "api_entities_tag_signature":
		return client.ApiEntitiesTagSignature(nil), nil
	case "api_entities_templates_list":
		return client.ApiEntitiesTemplatesList(nil), nil
	case "api_entities_terraform_module_version":
		return client.ApiEntitiesTerraformModuleVersion(nil), nil
	case "api_entities_tree_object":
		return client.ApiEntitiesTreeObject(nil), nil
	case "api_entities_trigger":
		return client.ApiEntitiesTrigger(nil), nil
	case "api_entities_user_agent_detail":
		return client.ApiEntitiesUserAgentDetail(nil), nil
	case "api_entities_user_count":
		return client.ApiEntitiesUserCount(nil), nil
	case "api_entities_user_public":
		return client.ApiEntitiesUserPublic(nil), nil
	case "api_entities_user_with_admin":
		return client.ApiEntitiesUserWithAdmin(nil), nil
	case "api_entities_wiki_attachment":
		return client.ApiEntitiesWikiAttachment(nil), nil
	case "api_entities_wiki_page":
		return client.ApiEntitiesWikiPage(nil), nil
	case "api_entities_wiki_page_basic":
		return client.ApiEntitiesWikiPageBasic(nil), nil
	case "application":
		return client.Application(nil), nil
	case "award_emoji":
		return client.AwardEmoji(nil), nil
	case "badge":
		return client.Badge(nil), nil
	case "branch":
		return client.Branch(nil), nil
	case "cargo_package":
		return client.CargoPackage(nil), nil
	case "ci_variable":
		return client.CiVariable(nil), nil
	case "cluster":
		return client.Cluster(nil), nil
	case "cluster_agent":
		return client.ClusterAgent(nil), nil
	case "composer":
		return client.Composer(nil), nil
	case "composer_package":
		return client.ComposerPackage(nil), nil
	case "conan":
		return client.Conan(nil), nil
	case "conan_package":
		return client.ConanPackage(nil), nil
	case "container_registry":
		return client.ContainerRegistry(nil), nil
	case "container_registry_event":
		return client.ContainerRegistryEvent(nil), nil
	case "custom_attribute":
		return client.CustomAttribute(nil), nil
	case "debian":
		return client.Debian(nil), nil
	case "debian_distribution":
		return client.DebianDistribution(nil), nil
	case "debian_package":
		return client.DebianPackage(nil), nil
	case "dependency_proxy":
		return client.DependencyProxy(nil), nil
	case "deploy_key":
		return client.DeployKey(nil), nil
	case "deploy_token":
		return client.DeployToken(nil), nil
	case "deployment":
		return client.Deployment(nil), nil
	case "ee_api_entities_approval_state":
		return client.EeApiEntitiesApprovalState(nil), nil
	case "ee_api_entities_audit_event":
		return client.EeApiEntitiesAuditEvent(nil), nil
	case "ee_api_entities_billable_membership":
		return client.EeApiEntitiesBillableMembership(nil), nil
	case "ee_api_entities_geo_node_status":
		return client.EeApiEntitiesGeoNodeStatus(nil), nil
	case "ee_api_entities_geo_pipeline_ref":
		return client.EeApiEntitiesGeoPipelineRef(nil), nil
	case "ee_api_entities_issuable_metric_image":
		return client.EeApiEntitiesIssuableMetricImage(nil), nil
	case "ee_api_entities_merge_request_approval_state":
		return client.EeApiEntitiesMergeRequestApprovalState(nil), nil
	case "ee_api_entities_ssh_certificate":
		return client.EeApiEntitiesSshCertificate(nil), nil
	case "environment":
		return client.Environment(nil), nil
	case "error_tracking_client_key":
		return client.ErrorTrackingClientKey(nil), nil
	case "feature":
		return client.Feature(nil), nil
	case "feature_flag":
		return client.FeatureFlag(nil), nil
	case "feature_flags_user_list":
		return client.FeatureFlagsUserList(nil), nil
	case "freeze_period":
		return client.FreezePeriod(nil), nil
	case "generic_package":
		return client.GenericPackage(nil), nil
	case "geo":
		return client.Geo(nil), nil
	case "go_proxy":
		return client.GoProxy(nil), nil
	case "group":
		return client.Group(nil), nil
	case "group_avatar":
		return client.GroupAvatar(nil), nil
	case "group_export":
		return client.GroupExport(nil), nil
	case "group_import":
		return client.GroupImport(nil), nil
	case "helm_package":
		return client.HelmPackage(nil), nil
	case "hook":
		return client.Hook(nil), nil
	case "import":
		return client.Import(nil), nil
	case "integration":
		return client.Integration(nil), nil
	case "invitation":
		return client.Invitation(nil), nil
	case "issue_link":
		return client.IssueLink(nil), nil
	case "issues_statistic":
		return client.IssuesStatistic(nil), nil
	case "job":
		return client.Job(nil), nil
	case "maven_package":
		return client.MavenPackage(nil), nil
	case "member":
		return client.Member(nil), nil
	case "merge_request":
		return client.MergeRequest(nil), nil
	case "metadata":
		return client.Metadata(nil), nil
	case "migration":
		return client.Migration(nil), nil
	case "ml_model_registry":
		return client.MlModelRegistry(nil), nil
	case "namespace":
		return client.Namespace(nil), nil
	case "npm":
		return client.Npm(nil), nil
	case "npm_package":
		return client.NpmPackage(nil), nil
	case "nuget":
		return client.Nuget(nil), nil
	case "nuget_package":
		return client.NugetPackage(nil), nil
	case "package_file":
		return client.PackageFile(nil), nil
	case "page":
		return client.Page(nil), nil
	case "participant":
		return client.Participant(nil), nil
	case "personal_access_token":
		return client.PersonalAccessToken(nil), nil
	case "project":
		return client.Project(nil), nil
	case "project_avatar":
		return client.ProjectAvatar(nil), nil
	case "project_entity":
		return client.ProjectEntity(nil), nil
	case "project_export":
		return client.ProjectExport(nil), nil
	case "project_hook":
		return client.ProjectHook(nil), nil
	case "project_import":
		return client.ProjectImport(nil), nil
	case "project_import_entity":
		return client.ProjectImportEntity(nil), nil
	case "project_package":
		return client.ProjectPackage(nil), nil
	case "project_snippet":
		return client.ProjectSnippet(nil), nil
	case "projects_job_token_scope":
		return client.ProjectsJobTokenScope(nil), nil
	case "protected_tag":
		return client.ProtectedTag(nil), nil
	case "pypi":
		return client.Pypi(nil), nil
	case "pypi_package":
		return client.PypiPackage(nil), nil
	case "release":
		return client.Release(nil), nil
	case "release_link":
		return client.ReleaseLink(nil), nil
	case "remote_mirror":
		return client.RemoteMirror(nil), nil
	case "rpm":
		return client.Rpm(nil), nil
	case "rpm_package":
		return client.RpmPackage(nil), nil
	case "rubygem":
		return client.Rubygem(nil), nil
	case "rubygem_package":
		return client.RubygemPackage(nil), nil
	case "runner":
		return client.Runner(nil), nil
	case "search":
		return client.Search(nil), nil
	case "secure_file":
		return client.SecureFile(nil), nil
	case "slack":
		return client.Slack(nil), nil
	case "snippet":
		return client.Snippet(nil), nil
	case "starrer":
		return client.Starrer(nil), nil
	case "system_hook":
		return client.SystemHook(nil), nil
	case "tag":
		return client.Tag(nil), nil
	case "terraform_registry":
		return client.TerraformRegistry(nil), nil
	case "terraform_state":
		return client.TerraformState(nil), nil
	case "test_report":
		return client.TestReport(nil), nil
	case "test_report_summary":
		return client.TestReportSummary(nil), nil
	case "topic":
		return client.Topic(nil), nil
	case "unleash_api":
		return client.UnleashApi(nil), nil
	case "usage_data":
		return client.UsageData(nil), nil
	case "user":
		return client.User(nil), nil
	case "web_commit":
		return client.WebCommit(nil), nil
	case "wiki":
		return client.Wiki(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts an AQL Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.VType.Matches(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.VType.Matches(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.VType)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
