// Typed models for the Gitlab SDK.
//
// GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
// params (op.<name>.points[].args.params[]). Field/param types come from the
// canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
// @voxgig/apidef VALID_CANON). Do not edit by hand.

export interface ApiEntitiesProjectWithAccess {
  allow_merge_on_skipped_pipeline?: boolean
  allow_pipeline_trigger_approve_deployment?: boolean
  analytics_access_level?: string
  approvals_before_merge?: string
  archived?: boolean
  auto_cancel_pending_pipelines?: string
  auto_devops_deploy_strategy?: string
  auto_devops_enabled?: boolean
  auto_duo_code_review_enabled?: string
  autoclose_referenced_issues?: boolean
  avatar_url?: string
  build_git_strategy?: string
  build_timeout?: number
  builds_access_level?: string
  can_create_merge_request_in?: boolean
  ci_allow_fork_pipelines_to_run_in_parent_project?: boolean
  ci_config_path?: string
  ci_default_git_depth?: number
  ci_delete_pipelines_in_seconds?: number
  ci_forward_deployment_enabled?: boolean
  ci_forward_deployment_rollback_allowed?: boolean
  ci_id_token_sub_claim_components?: any[]
  ci_job_token_scope_enabled?: boolean
  ci_pipeline_variables_minimum_override_role?: string
  ci_push_repository_for_job_token_allowed?: boolean
  ci_restrict_pipeline_cancellation_role?: string
  ci_separated_caches?: boolean
  compliance_frameworks?: string
  container_expiration_policy?: Record<string, any>
  container_registry_access_level?: string
  container_registry_enabled?: boolean
  container_registry_image_prefix?: string
  created_at?: string
  creator_id?: number
  custom_attributes?: Record<string, any>
  default_branch?: string
  description?: string
  description_html?: string
  duo_remote_flows_enabled?: string
  emails_disabled?: boolean
  emails_enabled?: boolean
  empty_repo?: boolean
  enforce_auth_checks_on_uploads?: boolean
  environments_access_level?: string
  external_authorization_classification_label?: string
  feature_flags_access_level?: string
  forked_from_project?: Record<string, any>
  forking_access_level?: string
  forks_count?: number
  group_runners_enabled?: boolean
  http_url_to_repo?: string
  id?: number
  import_error?: string
  import_status?: string
  import_type?: string
  import_url?: string
  infrastructure_access_level?: string
  issue_branch_template?: string
  issues_access_level?: string
  issues_enabled?: boolean
  issues_template?: string
  jobs_enabled?: boolean
  keep_latest_artifact?: boolean
  last_activity_at?: string
  lfs_enabled?: boolean
  license?: Record<string, any>
  license_url?: string
  links?: Record<string, any>
  marked_for_deletion_at?: string
  marked_for_deletion_on?: string
  max_artifacts_size?: number
  merge_commit_template?: string
  merge_method?: string
  merge_pipelines_enabled?: string
  merge_request_title_regex?: string
  merge_request_title_regex_description?: string
  merge_requests_access_level?: string
  merge_requests_enabled?: boolean
  merge_requests_template?: string
  merge_trains_enabled?: string
  merge_trains_skip_train_allowed?: string
  mirror?: string
  mirror_overwrites_diverged_branches?: string
  mirror_trigger_builds?: string
  mirror_user_id?: string
  model_experiments_access_level?: string
  model_registry_access_level?: string
  monitor_access_level?: string
  mr_default_target_self?: boolean
  name?: string
  name_with_namespace?: string
  namespace?: Record<string, any>
  only_allow_merge_if_all_discussions_are_resolved?: boolean
  only_allow_merge_if_all_status_checks_passed?: string
  only_allow_merge_if_pipeline_succeeds?: boolean
  only_mirror_protected_branches?: string
  open_issues_count?: number
  owner?: Record<string, any>
  package_registry_access_level?: string
  packages_enabled?: boolean
  pages_access_level?: string
  path?: string
  path_with_namespace?: string
  permissions?: Record<string, any>
  pre_receive_secret_detection_enabled?: boolean
  prevent_merge_without_jira_issue?: string
  printing_merge_request_link_enabled?: boolean
  public_jobs?: boolean
  readme_url?: string
  releases_access_level?: string
  remove_source_branch_after_merge?: boolean
  repository_access_level?: string
  repository_object_format?: string
  repository_storage?: string
  request_access_enabled?: boolean
  requirements_access_level?: string
  requirements_enabled?: string
  resolve_outdated_diff_discussions?: boolean
  resource_group_default_process_mode?: string
  restrict_user_defined_variables?: boolean
  runner_token_expiration_interval?: number
  runners_token?: string
  secret_push_protection_enabled?: boolean
  security_and_compliance_access_level?: string
  security_and_compliance_enabled?: string
  service_desk_address?: string
  service_desk_enabled?: boolean
  shared_runners_enabled?: boolean
  shared_with_groups?: any[]
  show_diff_preview_in_email?: boolean
  snippets_access_level?: string
  snippets_enabled?: boolean
  spp_repository_pipeline_access?: boolean
  squash_commit_template?: string
  squash_option?: string
  ssh_url_to_repo?: string
  star_count?: number
  statistics?: Record<string, any>
  suggestion_commit_message?: string
  tag_list?: any[]
  topics?: any[]
  updated_at?: string
  visibility?: string
  warn_about_potentially_unwanted_characters?: boolean
  web_based_commit_signing_enabled?: string
  web_url?: string
  wiki_access_level?: string
  wiki_enabled?: boolean
}

export interface ApiEntitiesProjectWithAccessLoadMatch {
  id: string
}

export interface Project {
  allow_merge_on_skipped_pipeline?: boolean
  allow_pipeline_trigger_approve_deployment?: boolean
  analytics_access_level?: string
  approvals_before_merge?: string
  archived?: boolean
  auto_cancel_pending_pipelines?: string
  auto_devops_deploy_strategy?: string
  auto_devops_enabled?: boolean
  auto_duo_code_review_enabled?: string
  autoclose_referenced_issues?: boolean
  avatar_url?: string
  build_git_strategy?: string
  build_timeout?: number
  builds_access_level?: string
  can_create_merge_request_in?: boolean
  ci_allow_fork_pipelines_to_run_in_parent_project?: boolean
  ci_config_path?: string
  ci_default_git_depth?: number
  ci_delete_pipelines_in_seconds?: number
  ci_forward_deployment_enabled?: boolean
  ci_forward_deployment_rollback_allowed?: boolean
  ci_id_token_sub_claim_components?: any[]
  ci_job_token_scope_enabled?: boolean
  ci_pipeline_variables_minimum_override_role?: string
  ci_push_repository_for_job_token_allowed?: boolean
  ci_restrict_pipeline_cancellation_role?: string
  ci_separated_caches?: boolean
  compliance_frameworks?: string
  container_expiration_policy?: Record<string, any>
  container_registry_access_level?: string
  container_registry_enabled?: boolean
  container_registry_image_prefix?: string
  created_at?: string
  creator_id?: number
  custom_attributes?: Record<string, any>
  default_branch?: string
  description?: string
  description_html?: string
  duo_remote_flows_enabled?: string
  emails_disabled?: boolean
  emails_enabled?: boolean
  empty_repo?: boolean
  enforce_auth_checks_on_uploads?: boolean
  environments_access_level?: string
  external_authorization_classification_label?: string
  feature_flags_access_level?: string
  forked_from_project?: Record<string, any>
  forking_access_level?: string
  forks_count?: number
  group_runners_enabled?: boolean
  http_url_to_repo?: string
  id?: number
  import_error?: string
  import_status?: string
  import_type?: string
  import_url?: string
  infrastructure_access_level?: string
  issue_branch_template?: string
  issues_access_level?: string
  issues_enabled?: boolean
  issues_template?: string
  jobs_enabled?: boolean
  keep_latest_artifact?: boolean
  last_activity_at?: string
  lfs_enabled?: boolean
  license?: Record<string, any>
  license_url?: string
  links?: Record<string, any>
  marked_for_deletion_at?: string
  marked_for_deletion_on?: string
  max_artifacts_size?: number
  merge_commit_template?: string
  merge_method?: string
  merge_pipelines_enabled?: string
  merge_request_title_regex?: string
  merge_request_title_regex_description?: string
  merge_requests_access_level?: string
  merge_requests_enabled?: boolean
  merge_requests_template?: string
  merge_trains_enabled?: string
  merge_trains_skip_train_allowed?: string
  mirror?: string
  mirror_overwrites_diverged_branches?: string
  mirror_trigger_builds?: string
  mirror_user_id?: string
  model_experiments_access_level?: string
  model_registry_access_level?: string
  monitor_access_level?: string
  mr_default_target_self?: boolean
  name?: string
  name_with_namespace?: string
  namespace?: Record<string, any>
  only_allow_merge_if_all_discussions_are_resolved?: boolean
  only_allow_merge_if_all_status_checks_passed?: string
  only_allow_merge_if_pipeline_succeeds?: boolean
  only_mirror_protected_branches?: string
  open_issues_count?: number
  owner?: Record<string, any>
  package_registry_access_level?: string
  packages_enabled?: boolean
  pages_access_level?: string
  path?: string
  path_with_namespace?: string
  pre_receive_secret_detection_enabled?: boolean
  prevent_merge_without_jira_issue?: string
  printing_merge_request_link_enabled?: boolean
  public_jobs?: boolean
  readme_url?: string
  releases_access_level?: string
  remove_source_branch_after_merge?: boolean
  repository_access_level?: string
  repository_object_format?: string
  repository_storage?: string
  request_access_enabled?: boolean
  requirements_access_level?: string
  requirements_enabled?: string
  resolve_outdated_diff_discussions?: boolean
  resource_group_default_process_mode?: string
  restrict_user_defined_variables?: boolean
  runner_token_expiration_interval?: number
  runners_token?: string
  secret_push_protection_enabled?: boolean
  security_and_compliance_access_level?: string
  security_and_compliance_enabled?: string
  service_desk_address?: string
  service_desk_enabled?: boolean
  shared_runners_enabled?: boolean
  shared_with_groups?: any[]
  show_diff_preview_in_email?: boolean
  snippets_access_level?: string
  snippets_enabled?: boolean
  spp_repository_pipeline_access?: boolean
  squash_commit_template?: string
  squash_option?: string
  ssh_url_to_repo?: string
  star_count?: number
  statistics?: Record<string, any>
  suggestion_commit_message?: string
  tag_list?: any[]
  topics?: any[]
  updated_at?: string
  visibility?: string
  warn_about_potentially_unwanted_characters?: boolean
  web_based_commit_signing_enabled?: string
  web_url?: string
  wiki_access_level?: string
  wiki_enabled?: boolean
}

export interface ProjectListMatch {
  allow_merge_on_skipped_pipeline?: boolean
  allow_pipeline_trigger_approve_deployment?: boolean
  analytics_access_level?: string
  approvals_before_merge?: string
  archived?: boolean
  auto_cancel_pending_pipelines?: string
  auto_devops_deploy_strategy?: string
  auto_devops_enabled?: boolean
  auto_duo_code_review_enabled?: string
  autoclose_referenced_issues?: boolean
  avatar_url?: string
  build_git_strategy?: string
  build_timeout?: number
  builds_access_level?: string
  can_create_merge_request_in?: boolean
  ci_allow_fork_pipelines_to_run_in_parent_project?: boolean
  ci_config_path?: string
  ci_default_git_depth?: number
  ci_delete_pipelines_in_seconds?: number
  ci_forward_deployment_enabled?: boolean
  ci_forward_deployment_rollback_allowed?: boolean
  ci_id_token_sub_claim_components?: any[]
  ci_job_token_scope_enabled?: boolean
  ci_pipeline_variables_minimum_override_role?: string
  ci_push_repository_for_job_token_allowed?: boolean
  ci_restrict_pipeline_cancellation_role?: string
  ci_separated_caches?: boolean
  compliance_frameworks?: string
  container_expiration_policy?: Record<string, any>
  container_registry_access_level?: string
  container_registry_enabled?: boolean
  container_registry_image_prefix?: string
  created_at?: string
  creator_id?: number
  custom_attributes?: Record<string, any>
  default_branch?: string
  description?: string
  description_html?: string
  duo_remote_flows_enabled?: string
  emails_disabled?: boolean
  emails_enabled?: boolean
  empty_repo?: boolean
  enforce_auth_checks_on_uploads?: boolean
  environments_access_level?: string
  external_authorization_classification_label?: string
  feature_flags_access_level?: string
  forked_from_project?: Record<string, any>
  forking_access_level?: string
  forks_count?: number
  group_runners_enabled?: boolean
  http_url_to_repo?: string
  id?: number
  import_error?: string
  import_status?: string
  import_type?: string
  import_url?: string
  infrastructure_access_level?: string
  issue_branch_template?: string
  issues_access_level?: string
  issues_enabled?: boolean
  issues_template?: string
  jobs_enabled?: boolean
  keep_latest_artifact?: boolean
  last_activity_at?: string
  lfs_enabled?: boolean
  license?: Record<string, any>
  license_url?: string
  links?: Record<string, any>
  marked_for_deletion_at?: string
  marked_for_deletion_on?: string
  max_artifacts_size?: number
  merge_commit_template?: string
  merge_method?: string
  merge_pipelines_enabled?: string
  merge_request_title_regex?: string
  merge_request_title_regex_description?: string
  merge_requests_access_level?: string
  merge_requests_enabled?: boolean
  merge_requests_template?: string
  merge_trains_enabled?: string
  merge_trains_skip_train_allowed?: string
  mirror?: string
  mirror_overwrites_diverged_branches?: string
  mirror_trigger_builds?: string
  mirror_user_id?: string
  model_experiments_access_level?: string
  model_registry_access_level?: string
  monitor_access_level?: string
  mr_default_target_self?: boolean
  name?: string
  name_with_namespace?: string
  namespace?: Record<string, any>
  only_allow_merge_if_all_discussions_are_resolved?: boolean
  only_allow_merge_if_all_status_checks_passed?: string
  only_allow_merge_if_pipeline_succeeds?: boolean
  only_mirror_protected_branches?: string
  open_issues_count?: number
  owner?: Record<string, any>
  package_registry_access_level?: string
  packages_enabled?: boolean
  pages_access_level?: string
  path?: string
  path_with_namespace?: string
  pre_receive_secret_detection_enabled?: boolean
  prevent_merge_without_jira_issue?: string
  printing_merge_request_link_enabled?: boolean
  public_jobs?: boolean
  readme_url?: string
  releases_access_level?: string
  remove_source_branch_after_merge?: boolean
  repository_access_level?: string
  repository_object_format?: string
  repository_storage?: string
  request_access_enabled?: boolean
  requirements_access_level?: string
  requirements_enabled?: string
  resolve_outdated_diff_discussions?: boolean
  resource_group_default_process_mode?: string
  restrict_user_defined_variables?: boolean
  runner_token_expiration_interval?: number
  runners_token?: string
  secret_push_protection_enabled?: boolean
  security_and_compliance_access_level?: string
  security_and_compliance_enabled?: string
  service_desk_address?: string
  service_desk_enabled?: boolean
  shared_runners_enabled?: boolean
  shared_with_groups?: any[]
  show_diff_preview_in_email?: boolean
  snippets_access_level?: string
  snippets_enabled?: boolean
  spp_repository_pipeline_access?: boolean
  squash_commit_template?: string
  squash_option?: string
  ssh_url_to_repo?: string
  star_count?: number
  statistics?: Record<string, any>
  suggestion_commit_message?: string
  tag_list?: any[]
  topics?: any[]
  updated_at?: string
  visibility?: string
  warn_about_potentially_unwanted_characters?: boolean
  web_based_commit_signing_enabled?: string
  web_url?: string
  wiki_access_level?: string
  wiki_enabled?: boolean
}

export interface ProjectCreateData {
  allow_merge_on_skipped_pipeline?: boolean
  allow_pipeline_trigger_approve_deployment?: boolean
  analytics_access_level?: string
  approvals_before_merge?: string
  archived?: boolean
  auto_cancel_pending_pipelines?: string
  auto_devops_deploy_strategy?: string
  auto_devops_enabled?: boolean
  auto_duo_code_review_enabled?: string
  autoclose_referenced_issues?: boolean
  avatar_url?: string
  build_git_strategy?: string
  build_timeout?: number
  builds_access_level?: string
  can_create_merge_request_in?: boolean
  ci_allow_fork_pipelines_to_run_in_parent_project?: boolean
  ci_config_path?: string
  ci_default_git_depth?: number
  ci_delete_pipelines_in_seconds?: number
  ci_forward_deployment_enabled?: boolean
  ci_forward_deployment_rollback_allowed?: boolean
  ci_id_token_sub_claim_components?: any[]
  ci_job_token_scope_enabled?: boolean
  ci_pipeline_variables_minimum_override_role?: string
  ci_push_repository_for_job_token_allowed?: boolean
  ci_restrict_pipeline_cancellation_role?: string
  ci_separated_caches?: boolean
  compliance_frameworks?: string
  container_expiration_policy?: Record<string, any>
  container_registry_access_level?: string
  container_registry_enabled?: boolean
  container_registry_image_prefix?: string
  created_at?: string
  creator_id?: number
  custom_attributes?: Record<string, any>
  default_branch?: string
  description?: string
  description_html?: string
  duo_remote_flows_enabled?: string
  emails_disabled?: boolean
  emails_enabled?: boolean
  empty_repo?: boolean
  enforce_auth_checks_on_uploads?: boolean
  environments_access_level?: string
  external_authorization_classification_label?: string
  feature_flags_access_level?: string
  forked_from_project?: Record<string, any>
  forking_access_level?: string
  forks_count?: number
  group_runners_enabled?: boolean
  http_url_to_repo?: string
  id?: number
  import_error?: string
  import_status?: string
  import_type?: string
  import_url?: string
  infrastructure_access_level?: string
  issue_branch_template?: string
  issues_access_level?: string
  issues_enabled?: boolean
  issues_template?: string
  jobs_enabled?: boolean
  keep_latest_artifact?: boolean
  last_activity_at?: string
  lfs_enabled?: boolean
  license?: Record<string, any>
  license_url?: string
  links?: Record<string, any>
  marked_for_deletion_at?: string
  marked_for_deletion_on?: string
  max_artifacts_size?: number
  merge_commit_template?: string
  merge_method?: string
  merge_pipelines_enabled?: string
  merge_request_title_regex?: string
  merge_request_title_regex_description?: string
  merge_requests_access_level?: string
  merge_requests_enabled?: boolean
  merge_requests_template?: string
  merge_trains_enabled?: string
  merge_trains_skip_train_allowed?: string
  mirror?: string
  mirror_overwrites_diverged_branches?: string
  mirror_trigger_builds?: string
  mirror_user_id?: string
  model_experiments_access_level?: string
  model_registry_access_level?: string
  monitor_access_level?: string
  mr_default_target_self?: boolean
  name?: string
  name_with_namespace?: string
  namespace?: Record<string, any>
  only_allow_merge_if_all_discussions_are_resolved?: boolean
  only_allow_merge_if_all_status_checks_passed?: string
  only_allow_merge_if_pipeline_succeeds?: boolean
  only_mirror_protected_branches?: string
  open_issues_count?: number
  owner?: Record<string, any>
  package_registry_access_level?: string
  packages_enabled?: boolean
  pages_access_level?: string
  path?: string
  path_with_namespace?: string
  pre_receive_secret_detection_enabled?: boolean
  prevent_merge_without_jira_issue?: string
  printing_merge_request_link_enabled?: boolean
  public_jobs?: boolean
  readme_url?: string
  releases_access_level?: string
  remove_source_branch_after_merge?: boolean
  repository_access_level?: string
  repository_object_format?: string
  repository_storage?: string
  request_access_enabled?: boolean
  requirements_access_level?: string
  requirements_enabled?: string
  resolve_outdated_diff_discussions?: boolean
  resource_group_default_process_mode?: string
  restrict_user_defined_variables?: boolean
  runner_token_expiration_interval?: number
  runners_token?: string
  secret_push_protection_enabled?: boolean
  security_and_compliance_access_level?: string
  security_and_compliance_enabled?: string
  service_desk_address?: string
  service_desk_enabled?: boolean
  shared_runners_enabled?: boolean
  shared_with_groups?: any[]
  show_diff_preview_in_email?: boolean
  snippets_access_level?: string
  snippets_enabled?: boolean
  spp_repository_pipeline_access?: boolean
  squash_commit_template?: string
  squash_option?: string
  ssh_url_to_repo?: string
  star_count?: number
  statistics?: Record<string, any>
  suggestion_commit_message?: string
  tag_list?: any[]
  topics?: any[]
  updated_at?: string
  visibility?: string
  warn_about_potentially_unwanted_characters?: boolean
  web_based_commit_signing_enabled?: string
  web_url?: string
  wiki_access_level?: string
  wiki_enabled?: boolean
}

export interface ProjectUpdateData {
  id: string
  allow_merge_on_skipped_pipeline?: boolean
  allow_pipeline_trigger_approve_deployment?: boolean
  analytics_access_level?: string
  approvals_before_merge?: string
  archived?: boolean
  auto_cancel_pending_pipelines?: string
  auto_devops_deploy_strategy?: string
  auto_devops_enabled?: boolean
  auto_duo_code_review_enabled?: string
  autoclose_referenced_issues?: boolean
  avatar_url?: string
  build_git_strategy?: string
  build_timeout?: number
  builds_access_level?: string
  can_create_merge_request_in?: boolean
  ci_allow_fork_pipelines_to_run_in_parent_project?: boolean
  ci_config_path?: string
  ci_default_git_depth?: number
  ci_delete_pipelines_in_seconds?: number
  ci_forward_deployment_enabled?: boolean
  ci_forward_deployment_rollback_allowed?: boolean
  ci_id_token_sub_claim_components?: any[]
  ci_job_token_scope_enabled?: boolean
  ci_pipeline_variables_minimum_override_role?: string
  ci_push_repository_for_job_token_allowed?: boolean
  ci_restrict_pipeline_cancellation_role?: string
  ci_separated_caches?: boolean
  compliance_frameworks?: string
  container_expiration_policy?: Record<string, any>
  container_registry_access_level?: string
  container_registry_enabled?: boolean
  container_registry_image_prefix?: string
  created_at?: string
  creator_id?: number
  custom_attributes?: Record<string, any>
  default_branch?: string
  description?: string
  description_html?: string
  duo_remote_flows_enabled?: string
  emails_disabled?: boolean
  emails_enabled?: boolean
  empty_repo?: boolean
  enforce_auth_checks_on_uploads?: boolean
  environments_access_level?: string
  external_authorization_classification_label?: string
  feature_flags_access_level?: string
  forked_from_project?: Record<string, any>
  forking_access_level?: string
  forks_count?: number
  group_runners_enabled?: boolean
  http_url_to_repo?: string
  import_error?: string
  import_status?: string
  import_type?: string
  import_url?: string
  infrastructure_access_level?: string
  issue_branch_template?: string
  issues_access_level?: string
  issues_enabled?: boolean
  issues_template?: string
  jobs_enabled?: boolean
  keep_latest_artifact?: boolean
  last_activity_at?: string
  lfs_enabled?: boolean
  license?: Record<string, any>
  license_url?: string
  links?: Record<string, any>
  marked_for_deletion_at?: string
  marked_for_deletion_on?: string
  max_artifacts_size?: number
  merge_commit_template?: string
  merge_method?: string
  merge_pipelines_enabled?: string
  merge_request_title_regex?: string
  merge_request_title_regex_description?: string
  merge_requests_access_level?: string
  merge_requests_enabled?: boolean
  merge_requests_template?: string
  merge_trains_enabled?: string
  merge_trains_skip_train_allowed?: string
  mirror?: string
  mirror_overwrites_diverged_branches?: string
  mirror_trigger_builds?: string
  mirror_user_id?: string
  model_experiments_access_level?: string
  model_registry_access_level?: string
  monitor_access_level?: string
  mr_default_target_self?: boolean
  name?: string
  name_with_namespace?: string
  namespace?: Record<string, any>
  only_allow_merge_if_all_discussions_are_resolved?: boolean
  only_allow_merge_if_all_status_checks_passed?: string
  only_allow_merge_if_pipeline_succeeds?: boolean
  only_mirror_protected_branches?: string
  open_issues_count?: number
  owner?: Record<string, any>
  package_registry_access_level?: string
  packages_enabled?: boolean
  pages_access_level?: string
  path?: string
  path_with_namespace?: string
  pre_receive_secret_detection_enabled?: boolean
  prevent_merge_without_jira_issue?: string
  printing_merge_request_link_enabled?: boolean
  public_jobs?: boolean
  readme_url?: string
  releases_access_level?: string
  remove_source_branch_after_merge?: boolean
  repository_access_level?: string
  repository_object_format?: string
  repository_storage?: string
  request_access_enabled?: boolean
  requirements_access_level?: string
  requirements_enabled?: string
  resolve_outdated_diff_discussions?: boolean
  resource_group_default_process_mode?: string
  restrict_user_defined_variables?: boolean
  runner_token_expiration_interval?: number
  runners_token?: string
  secret_push_protection_enabled?: boolean
  security_and_compliance_access_level?: string
  security_and_compliance_enabled?: string
  service_desk_address?: string
  service_desk_enabled?: boolean
  shared_runners_enabled?: boolean
  shared_with_groups?: any[]
  show_diff_preview_in_email?: boolean
  snippets_access_level?: string
  snippets_enabled?: boolean
  spp_repository_pipeline_access?: boolean
  squash_commit_template?: string
  squash_option?: string
  ssh_url_to_repo?: string
  star_count?: number
  statistics?: Record<string, any>
  suggestion_commit_message?: string
  tag_list?: any[]
  topics?: any[]
  updated_at?: string
  visibility?: string
  warn_about_potentially_unwanted_characters?: boolean
  web_based_commit_signing_enabled?: string
  web_url?: string
  wiki_access_level?: string
  wiki_enabled?: boolean
}

export interface ProjectRemoveMatch {
  id: string
}

